apiVersion: v1
kind: Secret
metadata:
  name: ecf4-secret
  namespace: ecf4
type: Opaque
stringData:
  DB_USER: root
  DB_PASS: password
  MYSQL_ROOT_PASSWORD: password
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  STRIPE_SECRET_KEY: sk_test_your_stripe_key_here
