# server {
#     listen 80;

#     location / {
#         root /usr/share/nginx/html;
#         index index.html index.htm;
#         # React Router support
#         try_files $uri $uri/ /index.html =404;
#     }

#     # Authentication service
#     location /api/auth/ {
#         proxy_pass http://authentication_service:7000/;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#     }

#     # Common Data service
#     location /api/common/ {
#         proxy_pass http://common_data_service:9000/;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#     }

#     # Payment service
#     location /api/payment/ {
#         proxy_pass http://payment_service:9050/;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#     }
# }